### ISSUE TITLE
Set Quotients

### ISSUE THREAD

**Issue by Saizan** [HoTT/HoTT-Agda#18]
would it make sense to port this definition of Set quotients from the Coq lib?

https://github.com/HoTT/HoTT/blob/master/theories/hit/quotient.v

The one in old/ makes use of spheres which seems overkill?

**Comment by favonia** [comment]
I put in something in /lib/types/SetQuotient.agda. Is it what you wanted? The one in old/ was done without truncation; nowadays truncations are more accepted as an inherent part of defining HITs.

**Comment by favonia** [comment]
@Saizan I am going to assume the new quotient code is satisfactory. Feel free to re-open.
