### ISSUE TITLE
Change the inductive definition of iterative loop spaces?

### ISSUE THREAD

**Issue by favonia** [HoTT/HoTT-Agda#37]
Experience shows that, at least for homotopy groups, `⊙Ω^ (S n) X` should be `⊙Ω^ n (⊙Ω X)`, not   `⊙Ω (⊙Ω^ n X)`.

**Comment by guillaumebrunerie** [comment]
I have no objection to that change. I believe I choose the other one just because I had no idea which one was better and I had to choose one.
Do you have any explicit example showing that it’s a better option?

**Comment by favonia** [comment]
Compare, for example, https://github.com/HoTT/HoTT-Agda/blob/159df930031634d6359629e3eda6bac1f20abcb3/core/lib/groups/HomotopyGroup.agda#L64-L103 and https://github.com/HoTT/HoTT-Agda/blob/159df930031634d6359629e3eda6bac1f20abcb3/core/lib/groups/HomotopyGroup.agda#L107-L113.

**Comment by favonia** [comment]
@fpvandoorn Thanks for the comment. I have done the concatenation and lemmas about it, and felt they are fine once you get used to the induction from `X` to `Ω(X)`. I will check the change in more details later.

Right now the alternative concatenation is defined as https://github.com/HoTT/HoTT-Agda/blob/159df930031634d6359629e3eda6bac1f20abcb3/core/lib/types/LoopSpace.agda#L278-L280 and one lemma is https://github.com/HoTT/HoTT-Agda/blob/159df930031634d6359629e3eda6bac1f20abcb3/core/lib/types/LoopSpace.agda#L351-L356.

**Comment by favonia** [comment]
@fpvandoorn I think my main point is that we do not seem to need any `add.comm` or `loop_space_add` if I stick with the alternative definition. I will ask Coq-HoTT people.

**Comment by favonia** [comment]
Closing this as there's nothing to do. We have two versions now.
