### ISSUE TITLE
Archiving this repository

### ISSUE THREAD

**Issue by favonia** [HoTT/HoTT-Agda#53]
For many years, there have not been any active developments in this repository. All significant contributors to this repository (me included) have moved on to similar-but-different theories (e.g., https://github.com/RedPRL/cooltt and https://github.com/agda/cubical) or even different careers. Even without adding new theorems, updating the current codebase to match the latest development of Agda would still take significant efforts, and more importantly, I do not expect that any new development would be based on this repository.

At this point, it seems I _(the only active benevolent dictator)_ should archive this repository to reflect the reality. I can make some final changes to address a few concerns (e.g., where to find a working Agda 2.5.3), but all other issues will be effectively closed after the archival. I plan to execute the archiving in about one month (around 2021/09/01).

Thanks to all the people who have starred or have even been watching this repository over the years. My Ph.D. thesis was based on this repository and I had a strong emotional attachment. However, actively maintaining this repository is no longer an option for me.

Here are the people whose contributions are above some threshold: @guillaumebrunerie @ecavallo @timjb @ericfinster @jespercockx @sattlerc @ystael @mikeshulman I am tagging them in case I made a misjudgment or abused my dictatorship.

**Comment by awswan** [comment]
Hello all!

I have agreed to take over as maintainer. Unfortunately I also cannot spend much time on the project and it seems like a difficult problem to get everything working with the current version of Agda.

Therefore, unless there are any objections, I will split the project into two separate versions. One I will keep more or less as is, together with some kind of container set up (docker or something) to package the library together with an old version of Agda that it works with. The other version, I will remove or break stuff as necessary to keep the core library mostly usable with the latest version of Agda. That one will be based on my fork at https://github.com/awswan/HoTT-Agda/tree/agda-2.6.1-compatible and I'll try to keep it up to date in the future.

Best,
Andrew Swan

**Comment by mikeshulman** [comment]
Are there other Agda libraries for Book HoTT that currently exist?

In particular, Table 8.2 in the HoTT Book lists a bunch of results, many of which were originally formalized in Agda.  How many of those results are available in a form that still works with a current version of (non-cubical) Agda?  It would be a shame for those formalizations to be lost.

**Comment by favonia** [comment]
I am closing this issue as there is nothing to do. We are not archiving this repository for now.

**Comment by jaycech3n** [comment]
Just to provide a data point, I'm working on things that use HoTT in non-cubical Agda, mostly relying on the core library. I'm grateful for the up-to-date fork!
